### ISSUE TITLE
Connect songs and albums to User model

### ISSUE THREAD

**Issue by mann27** [mann27/Albums#19]

**Comment by shrey1608** [comment]
I am working on this  @mann27 @ExpressHermes

**Comment by shrey1608** [comment]
Hey @ExpressHermes  i connected all album views and song views but i am facing one problem like if i want to add a song i am able to see albums of all the user i just want the user to see his own albums and not other user albums. Any solution?

**Comment by ExpressHermes** [comment]
Use `filter` to filter out only those querysets where user for the album is equal to current user

**Comment by shrey1608** [comment]
ok done! making a PR.

**Comment by shrey1608** [comment]
Done!

**Comment by ExpressHermes** [comment]
Is it working now?

**Comment by shrey1608** [comment]
yes everything i mentioned in the PR is working

**Comment by shrey1608** [comment]
everything is connected to the user model @ExpressHermes

**Comment by shrey1608** [comment]
solved in #54

**Comment by shrey1608** [comment]
@mann27 please close it!
