### ISSUE TITLE
UI for listing albums in home page. 

### ISSUE THREAD

**Issue by mann27** [mann27/Albums#34]
- [ ] make a card of each album.
- [ ] if there is some info which is required but not currently in the model make it static as of now.

**Comment by shrey1608** [comment]
![image](https://user-images.githubusercontent.com/45357209/96414244-7bbeb200-120a-11eb-9327-df5766899e3d.png)
Is this card okay? @ExpressHermes @mann27

**Comment by mann27** [comment]
Yeah looks great.

**Comment by shrey1608** [comment]
![image](https://user-images.githubusercontent.com/45357209/98807832-41c78100-2441-11eb-8545-ef9857bd7628.png)
Is this card looking proper for listing albums in home page?

**Comment by mann27** [comment]
Don't make details as a button and remove the delete button from here only can be deleted after going into the album. Align to the right of the title the fav. icon. Give some minor shadow to the card.

**Comment by shrey1608** [comment]
So what should i write instead of details , View?

**Comment by mann27** [comment]
details but not as a button but text with a link...

**Comment by shrey1608** [comment]
![image](https://user-images.githubusercontent.com/45357209/98812862-47c16000-2449-11eb-8b87-f8b5c49122b0.png)
Like this?

**Comment by mann27** [comment]
yes

**Comment by mann27** [comment]
yes

**Comment by shrey1608** [comment]
umm i liked the button one as it looks slightly more attractive

**Comment by mann27** [comment]
Cool, go with it then.

**Comment by shrey1608** [comment]
![image](https://user-images.githubusercontent.com/45357209/98813481-3a58a580-244a-11eb-803a-93efb4718adc.png)

**Comment by shrey1608** [comment]
Let @ExpressHermes decide !

**Comment by ExpressHermes** [comment]
I like what @mann27 said about fav button, align it to the right. Give some box shadow using bootstrap `shadow` class. And on hover, make the shadow a little darker so that it feels as if the card came a little forward.

**Comment by shrey1608** [comment]
ok Thanks

**Comment by shrey1608** [comment]
Please close it @mann27

**Comment by shrey1608** [comment]
solved in #62
