### ISSUE TITLE
change the title of website.

### ISSUE THREAD

**Issue by mann27** [mann27/Albums#36]
- [ ] change the title from WEBSITE to Albums
- [ ] In navbar change from Home to "Albums" with some CSS.

**Comment by khushali77** [comment]
Is this issue just for SLoP people or anyone else can do?

**Comment by mann27** [comment]
As it is an opensource project anyone can do it but the points will be awarded to selected participants of the project only.

**Comment by shrey1608** [comment]
Please close it!

**Comment by ExpressHermes** [comment]
Fixed in #38
