### ISSUE TITLE
Implement CRUD views for Album model

### ISSUE THREAD

**Issue by ExpressHermes** [mann27/Albums#44]
Create seperate views to implement following features:
- List all existing albums (it exists as index page after logging in refactor it)
- Add a new album
- Update an album
- Delete an album

There will be seperate view to implement each of the C.R.U.D. (create, read(list), update, delete) operations.

**Comment by shrey1608** [comment]
I will be working on it after i finish UI for listing albums in home page.

**Comment by ExpressHermes** [comment]
@shrey1608 leave the UI part for now. Focus on this. After you have implemeted this.You can work on UI.

**Comment by shrey1608** [comment]
ok I am working on this!

**Comment by shrey1608** [comment]
![image](https://user-images.githubusercontent.com/45357209/96590134-4053de80-1303-11eb-86f7-6df2b52e6c49.png)
The crud dashboard will look like this @ExpressHermes @mann27

**Comment by ExpressHermes** [comment]
It looks good! 

Some minimal ui changes that you can do in this commit. 
- Move create button on the right in front of 'Albums List' title. 

- Put the whole page inside container. Like in template, move the whole code in a `div` with `container` class.

**Comment by mann27** [comment]
Let's stick to the black and white theme. 
-> background to white
-> button white with black border
-> Navbar black background

**Comment by ExpressHermes** [comment]
@shrey1608 Make sure to pull the latest changes(done in #47) in using `git pull remote upstream` to avoid conflicts!

**Comment by shrey1608** [comment]
@ExpressHermes Please close it!

**Comment by ExpressHermes** [comment]
Resolved in #48
