### ISSUE TITLE
Implement favourite/star feature using AJAX

### ISSUE THREAD

**Issue by ExpressHermes** [mann27/Albums#46]
Create a view to handle starring and favourting an album and songs. Create s seperate templates that will show all the starred and favourited songs/albums. 

To favourite/star an song/album without reloading, we can use AJAX. If you are not familiar with ajax, you can do implement the feature where relaoding happens and we will improve it in further issues.

**Comment by shrey1608** [comment]
I am working on this issue!

**Comment by shrey1608** [comment]
We havent given an option to favourite the album so we need to include that in the album model and then create a view for it so in the template we will be able to see all the favourite albums and in the other template we will be able to see all the favourite songs

**Comment by shrey1608** [comment]
@ExpressHermes I am not able to create a favourite for the albums can you help me out

**Comment by ExpressHermes** [comment]
Sure... I will ping you on Gitter

**Comment by shrey1608** [comment]
Solved in #51 @ExpressHermes please close it :)
