### ISSUE TITLE
Change relationship type between Album-User and Song User

### ISSUE THREAD

**Issue by ExpressHermes** [mann27/Albums#57]
Currently relationship between user and albums/songs is OneToOne which is incorrect. An user can have multiple songs/albums related to it instead of a single album/song. Change the relationship field to fix this.

**Comment by shrey1608** [comment]
shall i replace it with a foreign field for the relationship or ManyToOne?

**Comment by ExpressHermes** [comment]
ForeignKey field

**Comment by shrey1608** [comment]
solved in #58 . Please close it @ExpressHermes
