### ISSUE TITLE
Listen Later feature

### ISSUE THREAD

**Issue by shrey1608** [mann27/Albums#65]
I want to implement this feature so i am planning to create a listen later view with its UI which would contain the list of songs. So I need to give a button to the user to add it so shall i create a single song page and give the button there ? Please tell @ExpressHermes @mann27

**Comment by mann27** [comment]
So it is basically like a personal list for the respective users. You can add a button in the songs listings like add to listen_later and then in listen_later the song listed there will be a listened. ( simply like a todo list ). Go ahead with the implementation!👍🏻

**Comment by shrey1608** [comment]
okay yes that would be good i would add the Listen Later button next to update and delete button in the song listings okay? @mann27

**Comment by mann27** [comment]
Yes

**Comment by shrey1608** [comment]
Solved in #66

**Comment by shrey1608** [comment]
solved in #67
